"""Add missing columns to task_comment

Revision ID: 3db7246c22db
Revises: be88c7ac7da7
Create Date: 2026-03-11 00:01:25.950240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db7246c22db'
down_revision: Union[str, Sequence[str], None] = 'be88c7ac7da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comment', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('task_comment', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('task_comment', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('task_comment', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_comment', 'user', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'task_comment', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'task_comment', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_comment', type_='foreignkey')
    op.drop_constraint(None, 'task_comment', type_='foreignkey')
    op.drop_constraint(None, 'task_comment', type_='foreignkey')
    op.drop_column('task_comment', 'deleted_by')
    op.drop_column('task_comment', 'deleted_at')
    op.drop_column('task_comment', 'updated_by')
    op.drop_column('task_comment', 'created_by')
    # ### end Alembic commands ###
