"""add_comment_reactions_and_mentions

Revision ID: 6657b0e94e5e
Revises: 3db7246c22db
Create Date: 2026-03-11 23:16:27.472504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6657b0e94e5e'
down_revision: Union[str, Sequence[str], None] = '3db7246c22db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_by_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['task_comment.id'], ),
    sa.ForeignKeyConstraint(['mentioned_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_mention_comment_id'), 'comment_mention', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_mention_mentioned_user_id'), 'comment_mention', ['mentioned_user_id'], unique=False)
    op.create_table('comment_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['task_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_reaction_comment_id'), 'comment_reaction', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_reaction_comment_id'), table_name='comment_reaction')
    op.drop_table('comment_reaction')
    op.drop_index(op.f('ix_comment_mention_mentioned_user_id'), table_name='comment_mention')
    op.drop_index(op.f('ix_comment_mention_comment_id'), table_name='comment_mention')
    op.drop_table('comment_mention')
    # ### end Alembic commands ###
