"""add_color_and_icon_to_project

Revision ID: 95a3613ad517
Revises: 309a849fa4f6
Create Date: 2026-03-01 22:26:31.795255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a3613ad517'
down_revision: Union[str, Sequence[str], None] = '309a849fa4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('project', sa.Column('color', sa.String(), nullable=True, server_default='#6366F1'))
    op.add_column('project', sa.Column('icon', sa.String(), nullable=True, server_default='folder'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'icon')
    op.drop_column('project', 'color')
    # ### end Alembic commands ###
